# Generated by Django 2.2.11 on 2020-09-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='city',
            field=models.CharField(default='Cali', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=30, null=True),
        ),
    ]
