# Generated by Django 2.2.11 on 2020-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mentoring', '0002_auto_20200926_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
